# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compile and Test Exercises
      run: |
        javac -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} exam/Exercise1.java exam/Exercise1Test.java
        java -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise1Test
        javac -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} exam/Exercise2.java exam/Exercise2Test.java
        java -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise2Test
        javac -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} exam/Exercise3.java exam/Exercise3Test.java
        java -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise3Test
        javac -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} exam/Exercise4.java exam/Exercise4Test.java
        java -cp .:${{ env.JUNIT_JAR }}:${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise4Test
      env:
        CLASSPATH_SEPARATOR: ${{ runner.os == 'Windows' && ';' || ':' }}
        JUNIT_JAR: junit-4.13.2.jar
        HAMCREST_JAR: hamcrest-all-1.3.jar



        
