name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        

    - name: Compile and Test Exercise1
      run: |
        javac -cp .${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} exam/Exercise1.java exam/Exercise1Test.java
        java -cp .${{ env.CLASSPATH_SEPARATOR }}exam${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise1Test
      env:
        CLASSPATH_SEPARATOR: ${{ runner.os == 'Windows' && ';' || ':' }}
        JUNIT_JAR: junit-4.13.2.jar
        HAMCREST_JAR: hamcrest-all-1.3.jar

    - name: Compile and Test Exercise2
      run: |
        javac -cp .${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} exam/Exercise2.java exam/Exercise2Test.java
        java -cp .${{ env.CLASSPATH_SEPARATOR }}exam${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise2Test
      env:
        CLASSPATH_SEPARATOR: ${{ runner.os == 'Windows' && ';' || ':' }}
        JUNIT_JAR: junit-4.13.2.jar
        HAMCREST_JAR: hamcrest-all-1.3.jar

    - name: Compile and Test Exercise3
      run: |
        javac -cp .${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} exam/Exercise3.java exam/Exercise3Test.java
        java -cp .${{ env.CLASSPATH_SEPARATOR }}exam${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise3Test
      env:
        CLASSPATH_SEPARATOR: ${{ runner.os == 'Windows' && ';' || ':' }}
        JUNIT_JAR: junit-4.13.2.jar
        HAMCREST_JAR: hamcrest-all-1.3.jar

    - name: Compile and Test Exercise4
      run: |
        javac -cp .${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} exam/Exercise4.java exam/Exercise4Test.java
        java -cp .${{ env.CLASSPATH_SEPARATOR }}exam${{ env.CLASSPATH_SEPARATOR }}${{ env.JUNIT_JAR }}${{ env.CLASSPATH_SEPARATOR }}${{ env.HAMCREST_JAR }} org.junit.runner.JUnitCore exam.Exercise4Test
      env:
        CLASSPATH_SEPARATOR: ${{ runner.os == 'Windows' && ';' || ':' }}
        JUNIT_JAR: junit-4.13.2.jar
        HAMCREST_JAR: hamcrest-all-1.3.jar


